title: "Find the Best Online Tools for You 🔧"
description: "Discover 100% free and powerful online tools to boost productivity, master SEO, and simplify daily work. No SIGN UP Required, just instant results! 🚀"
locale: en_us
lang: en_us
email: swipetoconnect@gmail.com
timezone: UTC
url: "https://www.freetools4u.site"
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.webp'
favicon: 'assets/images/favicon.ico'
author: Saif
paginate: 30
disqus: 'demowebsite'
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-6PWM9RV7GF

# Authors
authors:
  Saif:
    name: Saif
    display_name: Saif
    avatar: 'assets/images/saif.png'
    email: talktoaamirsaif@gmail.com
    web: https://www.freetools4u.site/
    twitter: https://x.com/freetools4usite
    description: "Md Saif Ansari is a passionate digital creator and founder of Free Tools 4U. With a strong vision to simplify everyday tasks, he builds free, powerful, and user-friendly online tools that help people save time, boost productivity, and succeed in their goals. Follow his journey to unlock smarter digital solutions — with love and simplicity at the core. ❤️"

# Social

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
